export const SEARCH_USERS = "SEARCH_USERS";
export const GET_USER = "GET_USER";
export const GET_REPOS = "GET_REPOS";
export const SET_LOADING = "SET_LOADING";
export const CLEAR_USERS = "CLEAR_USERS";
export const CLEAR_USER = "CLEAR_USER";

export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAILURE = "AUTH_FAILURE";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const REVIEWS_REQUEST = "REVIEWS_REQUEST";
export const REVIEWS_SUCCESS = "REVIEWS_SUCCESS";
export const REVIEWS_FAILURE = "REVIEWS_FAILURE";
export const REVIEW_CREATE_START = "REVIEW_CREATE_START";
export const REVIEW_CREATE_SUCCESS = "REVIEW_CREATE_SUCCESS";
export const REVIEW_CREATE_FAILURE = "REVIEW_CREATE_FAILURE";
export const REVIEW_UPDATE_SUCCESS = "REVIEW_UPDATE_SUCCESS";
export const REVIEW_DELETE_SUCCESS = "REVIEW_DELETE_SUCCESS";
